{% set name = "bioutils" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: 'r-{{ name|lower }}'
  version: '{{ environ['VERSION'] }}'

source:
  path: '../'
  #git_url: 'https://github.com/letaylor/{{ name|lower }}.git'
  #git_tag: 'master'

build:
  script_env:
    - VERSION
  merge_build_host: True # [win]
  number: 0 # if new build for the same version, increment the build number.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  # {{posix}}zip build requirement for [win]
  build:
    - {{ posix }}zip
  host:
    - r-base
    - r-stringr
    - r-plyr
    - bioconductor-biomart
  run:
    - r-base
    - r-stringr
    - r-plyr
    - bioconductor-biomart

test:
  commands:
    # You can put additional test commands to be run here.
    - '$R -e "library(''{{ name }}'')"'           # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\""      # [win]
  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.
  # requires:
    # Put any additional test requirements here.

about:
  home: 'https://github.com/letaylor/{{ name }}'
  license: MIT
  summary: 'Useful functions for computational biology.'
  license_family: MIT
