{% set name = "bioutils" %}
{% set version = "0.1.2" %}
{% set posix = 'm2-' if win else '' %} # [win]
{% set native = 'm2w64-' if win else '' %} # [win]

package:
  name: 'r-{{ name|lower }}'
  version: '{{ version }}'

source:
  path: '../'
  #git_url: 'https://github.com/letaylor/{{ name|lower }}.git'
  #git_tag: 'master'

build:
  merge_build_host: True # [win]
  number: 0 # if new build for the same version, increment the build number.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - r-base
    - r-stringr
    - r-plyr
    - bioconductor-biomart
  run:
    - r-base
    - r-stringr
    - r-plyr
    - bioconductor-biomart

test:
  commands:
    - '$R -e "library(''{{ name }}'')"'           # [not win]
    #- "\"%R%\" -e \"library('{{ name }}')\""      # [win]

about:
  home: 'https://github.com/letaylor/{{ name }}'
  license: MIT
  summary: 'Useful functions for computational biology.'
